name: gcc12

on:
  push:

jobs:
  scan:
    name: static analyzer
    env:
      CC: gcc
      CFLAGS: -fanalyzer
    runs-on: ubuntu-latest
    container:
      image: fedora:rawhide
    steps:
    - name: Install dependencies
      run: |
        dnf --nogpgcheck -y groupinstall "Development Tools"
        dnf --nogpgcheck -y install autoconf openssl-devel pcre-devel zlib-devel systemd-devel make findutils pcre2-devel mariadb-connector-c-devel libevent-devel libcurl-devel libxml2-devel net-snmp-devel libssh2-devel OpenIPMI-devel unixODBC-devel openldap-devel 
    - name: Code checkout
      uses: actions/checkout@v2
    - name: Generate configure
      run: |
        autoreconf -iv
    - name: Build
      run: |
        ./configure --with-libpthread --with-libpcre --with-libcurl --with-libxml2 --with-net-snmp --with-openssl --enable-ipv6 --with-ssh2 --with-openipmi --with-unixodbc --with-ldap --enable-server --enable-proxy --enable-agent --enable-agent2 --enable-java --sysconfdir=/etc/zabbix --with-mysql
        make

